### ISSUE TITLE
Sidekiq is not processing jobs

### ISSUE THREAD

**Issue by darkcode85** [brainyatom/opsworks-sidekiq#7]
I have a Rails App running on Opsworks and I used this custom cookbook to set up sidekiq.

It is working properly and after start/deploy my instance Sidekiq is running as I can see when I run `ps aux | grep sidekiq`, but if I go to my application and create some actions that generate a Sidekiq Job (send email, generate notification) the jobs are not processing and the email/notifications are not generated. Why if Sidekiq is running is not processing the jobs?

Redis is also running when I check it using `ps aux | grep redis`

sidekiq.yml content:

`:pidfile: tmp/pids/sidekiq.pid`
`development:`
  `:concurrency: 2`
`production:`
 `:concurrency: 5`
  `:logfile: ./log/sidekiq.log`
`:queues:`
  `- default`

**Comment by atomgiant** [comment]
Hi @darkcode85 - I am not really sure why it is not working for you.  You can try adding `:verbose: true` to your sidekiq.yml and see if the sidekiq log has more info.

You could also check the queue etc to see if the jobs are being pulled by using the Sidekiq API in the rails console: https://github.com/mperham/sidekiq/wiki/API

**Comment by atomgiant** [comment]
Also - I am using this `start_command` config on Sidekiq 4.1.1 for a recent project:

`"start_command": "bundle exec sidekiq -r . -e production -C config/sidekiq.yml 2>&1 >> log/sidekiq.log"`

**Comment by interpegasus** [comment]
Hi,

Thanks for sharing the opsworks recipe.

I would like to know why jobs are not processed? 

**log/sidekiq.log**
```
Bundler will use `/tmp/bundler/home/unknown` as your home directory temporarily
2017-04-01T18:11:27.114Z 28283 TID-7bgv0 INFO: Running in ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
2017-04-01T18:11:27.114Z 28283 TID-7bgv0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-04-01T18:11:27.115Z 28283 TID-7bgv0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-04-01T18:11:27.115Z 28283 TID-7bgv0 INFO: Booting Sidekiq 4.2.10 with redis options {:url=>nil}
Your home directory is not set properly:
 * `/` is not writable
```

And also I would like to know why when I start sidekiq manually, only the defaukt queue is processed:
`bundle exec sidekiq -r . -e production -C config/sidekiq.yml 2>&1 >> log/sidekiq.log"`

**config/sideqik.yml** 
```
$ cat config/sideqik.yml 
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: true
:concurrency: 100
:timeout: 1800
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 100
development:
  :concurrency: 100
production:
  :concurrency: 100
:queues:
  - ["sync_15_sec", 5]
  - ["sync_5_min", 4]
  - ["sync_10_min", 3]
  - ["sync_60_min", 2]
  - ["sync_24_h", 1]
  - ["default", 1]
```

Thanks in advance

**Comment by interpegasus** [comment]
It works fine after customizing the recipe. I had to set the HOME environment variable to "/home/deploy". It might change depending of the Linux distribution and custom configuration. 

This issue can be solved by debugging the generated script at /etc/init/ and ensuring the service starts correctly via:

`sudo start sidekiq-[REPLACE_WITH_APP_NAME]`

Once the init script works, the recipe can be modified accordingly, to generate the corresponding working version of the script.

Thanks for sharing the code 👍  :-) It was very helpful.

**Comment by atomgiant** [comment]
@interpegasus Thanks for the feedback.  I am glad you found this useful :)
